#!/bin/bash

get_passwords() {
    local files=(~/.password-store/*)
    # expand */ to produce a pattern,
    # and match it against the beginning
    # of every element of the array.
    # ## means the result is the longest
    # matching pattern deleted.
    files=("${files[@]##*/}")
    for file in "${files[@]}"; do
        # expand .* to produce a pattern,
        # and match it against the trailing
        # portion of the parameter (in this
        # case, file). 
        # % means the result is the shortest
        # matching pattern deleted.
        printf "%s\n" "${file%.*}" 
    done
}

choice="$(get_passwords | dmenu -l 5)"

if [[ -z "$choice" ]]; then
    exit 0
else
    pass -c "$choice"
fi